---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec
  format: documentation

platforms:
  - name: ubuntu-14.04
  - name: debian-8.3
  - name: centos-6.7
  - name: centos-7.1
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[test-module::default]
    attributes:
      test-module:
        action:
        - load
  - name: load
    run_list:
      - recipe[test-module::default]
    attributes:
      test-module:
        action:
        - load
        onboot: false
  - name: unload
    run_list:
      - recipe[test-module::default]
    attributes:
      test-module:
        action:
        - load
        - unload
  - name: remove
    run_list:
      - recipe[test-module::default]
    attributes:
      test-module:
        action:
        - remove
  - name: check_availability
    run_list:
      - recipe[test-module::default]

