# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: kernel-modules
# Spec:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

def platforms
  {
    redhat: [
      '7.7',
      '6.10',
    ],
    oracle: [
      '7.6',
      '6.10',
    ],
    centos: [
      '7.7.1908',
      '6.10',
    ],
  }
end
