# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: kernel-modules
# Spec:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

def platforms
  {
    redhat: [
      '7.3',
      '6.8',
    ],
    oracle: [
      '7.2',
      '6.8',
    ],
    centos: [
      '7.3.1611',
      '6.8',
    ],
  }
end
