# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: kernel-modules
# Spec:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

def platforms
  {
    redhat: [
      '8',
      '7.9',
      '6.10',
    ],
    oracle: [
      '7.6',
      '6.10',
    ],
    centos: [
      '8',
      '7.8.2003',
      '6.10',
    ],
  }
end
